"""
screen6_carla_launcher.py
Streamlit page for launching CARLA and ScenarioRunner automatically.
"""

import subprocess
import threading
import time
import os
import signal
import glob
import streamlit as st


# Module-level log buffers — safe to write from background threads
_log_buffers = {
    "carla_logs": [],
    "scenario_logs": [],
}


def show():

    CARLA_ROOT = os.path.expanduser("~/CARLA_0.9.15")
    SCENARIO_RUNNER_ROOT = os.path.expanduser("~/scenario_runner")

    eggs = glob.glob(os.path.join(CARLA_ROOT, "PythonAPI/carla/dist/*py3*.egg"))
    CARLA_EGG = eggs[0] if eggs else None

    PYTHONPATH_EXTRA = ":".join(filter(None, [
        CARLA_EGG,
        os.path.join(CARLA_ROOT, "PythonAPI/carla"),
        os.path.join(CARLA_ROOT, "PythonAPI"),
    ]))

    CARLA_CMD = [
        os.path.join(CARLA_ROOT, "CarlaUE4.sh"),
        #"-RenderOffScreen",
        "-quality-level=Low",
        "-benchmark",
        "-fps=15"
    ]

    defaults = {
        "carla_process": None,
        "scenario_process": None,
        "carla_logs": [],
        "scenario_logs": [],
        "carla_status": "stopped",
        "scenario_status": "stopped",
        "launch_started": False,
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

    def stream_logs(process, log_key, status_key, ready_marker=None):
        for line in iter(process.stdout.readline, b""):
            decoded = line.decode("utf-8", errors="replace").rstrip()
            _log_buffers[log_key].append(decoded)  # write to module-level buffer, thread-safe
            if ready_marker and ready_marker in decoded:
                st.session_state[status_key] = "running"
        rc = process.wait()
        if st.session_state.get(status_key) not in ("stopped",):
            st.session_state[status_key] = "finished" if rc == 0 else "crashed"

    def launch_carla():
        st.session_state["carla_status"] = "starting"
        _log_buffers["carla_logs"] = []  # reset buffer
        env = os.environ.copy()
        proc = subprocess.Popen(
            CARLA_CMD,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=env,
            preexec_fn=os.setsid
        )
        st.session_state["carla_process"] = proc
        threading.Thread(
            target=stream_logs,
            args=(proc, "carla_logs", "carla_status", "Server listening"),
            daemon=True
        ).start()

    def launch_scenario(xosc_path):
        st.session_state["scenario_status"] = "starting"
        _log_buffers["scenario_logs"] = []  # reset buffer
        env = os.environ.copy()
        existing_pp = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = PYTHONPATH_EXTRA + (":" + existing_pp if existing_pp else "")
        cmd = [
            "python", "scenario_runner.py",
            "--openscenario", xosc_path,
            "--reloadWorld"
        ]
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=env,
            cwd=SCENARIO_RUNNER_ROOT,
            preexec_fn=os.setsid
        )
        st.session_state["scenario_process"] = proc
        threading.Thread(
            target=stream_logs,
            args=(proc, "scenario_logs", "scenario_status"),
            daemon=True
        ).start()

    def stop_all():
        for key in ["carla_process", "scenario_process"]:
            proc = st.session_state.get(key)
            if proc and proc.poll() is None:
                try:
                    os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
                except Exception:
                    proc.terminate()
        st.session_state["carla_status"] = "stopped"
        st.session_state["scenario_status"] = "stopped"
        st.session_state["carla_process"] = None
        st.session_state["scenario_process"] = None
        st.session_state["launch_started"] = False

    STATUS_ICONS = {
        "stopped": "⚪", "starting": "🟡", "running": "🟢",
        "finished": "✅", "crashed": "🔴", "error": "🔴",
    }

    def status_badge(label, status):
        icon = STATUS_ICONS.get(status, "⚪")
        st.markdown(f"**{label}:** {icon} `{status.upper()}`")

    st.title("🚗 Launch in CARLA")
    st.markdown("Automates launching CARLA and running the generated scenario in ScenarioRunner.")
    st.divider()

    st.subheader("📁 Scenario File")
    xosc_path = st.text_input(
        "Path to generated .xosc file",
        value=st.session_state.get(
            "generated_xosc_path",
            os.path.join(SCENARIO_RUNNER_ROOT, "srunner/examples/Car-to-Car Rear Stationary.xosc")
        ),
        help="Full path to the OpenSCENARIO file generated by your RAG system"
    )
    st.divider()

    st.subheader("📊 Status")
    col1, col2 = st.columns(2)
    with col1:
        status_badge("CARLA Simulator", st.session_state["carla_status"])
    with col2:
        status_badge("Scenario Runner", st.session_state["scenario_status"])
    st.divider()

    st.subheader("🎮 Controls")
    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("🚀 Launch CARLA + Scenario", type="primary", use_container_width=True,
                     disabled=st.session_state["launch_started"]):
            if not os.path.exists(xosc_path):
                st.error(f"❌ XOSC file not found: {xosc_path}")
            else:
                st.session_state["launch_started"] = True
                launch_carla()
                with st.spinner("⏳ Waiting for CARLA to start (30s)..."):
                    time.sleep(30)
                launch_scenario(xosc_path)
                st.rerun()

    with col2:
        if st.button("🔄 Refresh Status", use_container_width=True):
            st.rerun()

    with col3:
        if st.button("🛑 Stop All", type="secondary", use_container_width=True,
                     disabled=not st.session_state["launch_started"]):
            stop_all()
            st.success("All processes stopped.")
            st.rerun()

    st.divider()

    st.subheader("📋 Live Logs")
    log_col1, log_col2 = st.columns(2)

    with log_col1:
        st.markdown("**🖥️ CARLA Simulator Logs**")
        carla_logs = _log_buffers["carla_logs"]
        if carla_logs:
            st.code("\n".join(carla_logs[-50:]), language="bash")
        else:
            st.info("No logs yet. Launch CARLA to see output.")

    with log_col2:
        st.markdown("**🏁 Scenario Runner Logs**")
        scenario_logs = _log_buffers["scenario_logs"]
        if scenario_logs:
            st.code("\n".join(scenario_logs[-50:]), language="bash")
        else:
            st.info("No logs yet. Scenario will start after CARLA is ready.")

    if st.session_state["launch_started"]:
        time.sleep(2)
        st.rerun()
