"""
screen6_carla_launcher.py
Streamlit page for launching CARLA and ScenarioRunner automatically.
"""

import subprocess
import threading
import time
import os
import signal
import glob
import streamlit as st
from ui_utils import navigate_to

# Module-level log buffers — safe to write from background threads
_log_buffers = {
    "carla_logs": [],
    "scenario_logs": [],
}


def show():

    CARLA_ROOT = os.path.expanduser("~/CARLA_0.9.15")
    SCENARIO_RUNNER_ROOT = os.path.expanduser("~/scenario_runner")

    eggs = glob.glob(os.path.join(CARLA_ROOT, "PythonAPI/carla/dist/*py3*.egg"))
    CARLA_EGG = eggs[0] if eggs else None

    PYTHONPATH_EXTRA = ":".join(filter(None, [
        CARLA_EGG,
        os.path.join(CARLA_ROOT, "PythonAPI/carla"),
        os.path.join(CARLA_ROOT, "PythonAPI"),
    ]))

    CARLA_CMD = [
        os.path.join(CARLA_ROOT, "CarlaUE4.sh"),
        "-quality-level=Epic",
        "-fps=60",
        "-windowed",
        "-ResX=1280",
        "-ResY=720",
    ]

    defaults = {
        "carla_process": None,
        "scenario_process": None,
        "carla_logs": [],
        "scenario_logs": [],
        "carla_status": "stopped",
        "scenario_status": "stopped",
        "carla_launched": False,
        "scenario_launched": False,
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

    def stream_logs(process, log_key, status_key, ready_marker=None):
        for line in iter(process.stdout.readline, b""):
            decoded = line.decode("utf-8", errors="replace").rstrip()
            _log_buffers[log_key].append(decoded)
            if ready_marker and ready_marker in decoded:
                st.session_state[status_key] = "running"
        rc = process.wait()
        if st.session_state.get(status_key) not in ("stopped",):
            st.session_state[status_key] = "finished" if rc == 0 else "crashed"

    def launch_carla():
        st.session_state["carla_status"] = "starting"
        _log_buffers["carla_logs"] = []
        env = os.environ.copy()
        proc = subprocess.Popen(
            CARLA_CMD,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=env,
            preexec_fn=os.setsid
        )
        st.session_state["carla_process"] = proc
        st.session_state["carla_launched"] = True
        threading.Thread(
            target=stream_logs,
            args=(proc, "carla_logs", "carla_status", "Server listening"),
            daemon=True
        ).start()

    def launch_scenario(xosc_path):
        st.session_state["scenario_status"] = "starting"
        _log_buffers["scenario_logs"] = []
        env = os.environ.copy()
        existing_pp = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = PYTHONPATH_EXTRA + (":" + existing_pp if existing_pp else "")
        cmd = [
            "python", "scenario_runner.py",
            "--openscenario", xosc_path,
            "--reloadWorld"
        ]
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=env,
            cwd=SCENARIO_RUNNER_ROOT,
            preexec_fn=os.setsid
        )
        st.session_state["scenario_process"] = proc
        st.session_state["scenario_launched"] = True
        threading.Thread(
            target=stream_logs,
            args=(proc, "scenario_logs", "scenario_status"),
            daemon=True
        ).start()

    def stop_all():
        for key in ["carla_process", "scenario_process"]:
            proc = st.session_state.get(key)
            if proc and proc.poll() is None:
                try:
                    os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
                except Exception:
                    proc.terminate()
        st.session_state["carla_status"] = "stopped"
        st.session_state["scenario_status"] = "stopped"
        st.session_state["carla_process"] = None
        st.session_state["scenario_process"] = None
        st.session_state["carla_launched"] = False
        st.session_state["scenario_launched"] = False

    STATUS_ICONS = {
        "stopped": "⚪", "starting": "🟡", "running": "🟢",
        "finished": "✅", "crashed": "🔴", "error": "🔴",
    }

    def status_badge(label, status):
        icon = STATUS_ICONS.get(status, "⚪")
        st.markdown(f"**{label}:** {icon} `{status.upper()}`")

    st.title("🚗 Launch in CARLA")
    st.markdown("Automates launching CARLA and running the generated scenario in ScenarioRunner.")
    st.divider()

    st.subheader("📁 Scenario File")
    xosc_path = st.text_input(
        "Path to generated .xosc file",
        value=st.session_state.get(
            "generated_xosc_path",
            os.path.join(SCENARIO_RUNNER_ROOT, "srunner/examples/Car-to-Car Rear Stationary.xosc")
        ),
        help="Full path to the OpenSCENARIO file generated by your RAG system"
    )
    st.divider()

    st.subheader("📊 Status")
    col1, col2 = st.columns(2)
    with col1:
        status_badge("CARLA Simulator", st.session_state["carla_status"])
    with col2:
        status_badge("Scenario Runner", st.session_state["scenario_status"])
    st.divider()

    st.subheader("🎮 Controls")
    col1, col2, col3, col4 = st.columns(4)

    # Button 1: Launch CARLA only
    with col1:
        carla_running = st.session_state["carla_status"] in ("starting", "running")
        if st.button("🚀 Launch CARLA", type="primary", use_container_width=True,
                     disabled=carla_running):
            launch_carla()
            st.rerun()

    # Button 2: Run Scenario (only after CARLA is launched)
    with col2:
        carla_ready = st.session_state["carla_launched"]
        scenario_running = st.session_state["scenario_status"] in ("starting", "running")
        if st.button("▶️ Run Scenario", type="primary", use_container_width=True,
                     disabled=(not carla_ready or scenario_running)):
            if not os.path.exists(xosc_path):
                st.error(f"❌ XOSC file not found: {xosc_path}")
            else:
                launch_scenario(xosc_path)
                st.rerun()

    # Button 3: Refresh
    with col3:
        if st.button("🔄 Refresh", use_container_width=True):
            st.rerun()

    # Button 4: Stop All
    with col4:
        has_processes = st.session_state["carla_launched"] or st.session_state["scenario_launched"]
        if st.button("🛑 Stop All", type="secondary", use_container_width=True,
                     disabled=not has_processes):
            stop_all()
            st.success("All processes stopped.")
            st.rerun()

    # Help text
    if not st.session_state["carla_launched"]:
        st.info("💡 Step 1: Launch CARLA first. Wait ~30 seconds for it to start.")
    elif st.session_state["carla_status"] == "starting":
        st.warning("⏳ CARLA is starting... Wait for status to turn 🟢 before running scenario.")
    elif st.session_state["carla_status"] == "running" and not st.session_state["scenario_launched"]:
        st.success("✅ CARLA is ready! Click 'Run Scenario' to start.")

    st.divider()

    st.subheader("📋 Live Logs")
    log_col1, log_col2 = st.columns(2)

    with log_col1:
        st.markdown("**🖥️ CARLA Simulator Logs**")
        carla_logs = _log_buffers["carla_logs"]
        if carla_logs:
            st.code("\n".join(carla_logs[-50:]), language="bash")
        else:
            st.info("No logs yet. Launch CARLA to see output.")

    with log_col2:
        st.markdown("**🏁 Scenario Runner Logs**")
        scenario_logs = _log_buffers["scenario_logs"]
        if scenario_logs:
            st.code("\n".join(scenario_logs[-50:]), language="bash")
        else:
            st.info("No logs yet. Run scenario after CARLA is ready.")

    if st.session_state["carla_launched"] or st.session_state["scenario_launched"]:
        time.sleep(2)
        st.rerun()

    st.divider()

    # Navigation
    st.subheader("🔀 Navigation")
    nav1, nav2, nav3 = st.columns(3)

    with nav1:
        if st.button("← Back to XOSC", use_container_width=True):
            stop_all()
            navigate_to("generate_xosc")

    with nav2:
        if st.button("← Back to Scenario Selection", use_container_width=True):
            stop_all()
            navigate_to("features")

    with nav3:
        if st.button("🔄 Start Over", use_container_width=True):
            stop_all()
            navigate_to("standards")
